import React, { useState, useRef, useEffect, useMemo } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Animated, PanResponder, Dimensions, SafeAreaView } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';
import { Colors } from '../../src/constants/colors';
import { ScreenHeader } from '../../src/components/ScreenHeader';
import { CombinationCard } from '../../src/components/CombinationCard';
import { SofascoreDatePicker } from '../../src/components/SofascoreDatePicker';
import { useCombinations } from '../../src/hooks/useCombinations';
import { ActivityIndicator } from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;
const SWIPE_THRESHOLD = 0.25 * SCREEN_WIDTH;
const SWIPE_OUT_DURATION = 250;

export default function CombinationsScreen() {
    const { t, i18n } = useTranslation();
    const [selectedDate, setSelectedDate] = useState(new Date());

    // Format date specifically for the backend format: YYYY-MM-DD
    const dateStr = useMemo(() => {
        const y = selectedDate.getFullYear();
        const m = String(selectedDate.getMonth() + 1).padStart(2, '0');
        const d = String(selectedDate.getDate()).padStart(2, '0');
        return `${y}-${m}-${d}`;
    }, [selectedDate]);

    const {
        combinations, currentCombo: activeCombo, currentIndex,
        savedCount, skippedCount, totalCount,
        handleSwipeLeft, handleSwipeRight, resetCards,
        isFinished, loading, error
    } = useCombinations(dateStr, i18n.language || 'en');

    const position = useRef(new Animated.ValueXY()).current;

    // We must recreate the panResponder if currentIndex changes so it attaches to the top card correctly
    const panResponder = useMemo(() => PanResponder.create({
        onStartShouldSetPanResponder: () => true,
        onPanResponderMove: (event, gesture) => {
            position.setValue({ x: gesture.dx, y: 0 }); // Only allow horizontal sliding
        },
        onPanResponderRelease: (event, gesture) => {
            if (gesture.dx > SWIPE_THRESHOLD) {
                forceSwipe('right');
            } else if (gesture.dx < -SWIPE_THRESHOLD) {
                forceSwipe('left');
            } else {
                resetPosition();
            }
        }
    }), [currentIndex]);

    const forceSwipe = (direction: 'left' | 'right') => {
        const x = direction === 'right' ? SCREEN_WIDTH : -SCREEN_WIDTH;
        Animated.timing(position, {
            toValue: { x, y: 0 },
            duration: SWIPE_OUT_DURATION,
            useNativeDriver: false // Some pan responder animation values can struggle with native driver
        }).start(() => onSwipeComplete(direction));
    };

    const onSwipeComplete = (direction: 'left' | 'right') => {
        direction === 'right' ? handleSwipeRight() : handleSwipeLeft();
        position.setValue({ x: 0, y: 0 });
    };

    const resetPosition = () => {
        Animated.spring(position, {
            toValue: { x: 0, y: 0 },
            friction: 6,
            useNativeDriver: false
        }).start();
    };

    const getCardStyle = () => {
        const rotate = position.x.interpolate({
            inputRange: [-SCREEN_WIDTH * 1.5, 0, SCREEN_WIDTH * 1.5],
            outputRange: ['-60deg', '0deg', '60deg']
        });

        return {
            ...position.getLayout(),
            transform: [{ rotate }]
        };
    };

    // Derived view variables
    const nextCombo = combinations[currentIndex + 1];

    if (isFinished) {
        return (
            <View style={styles.container}>
                <View style={styles.emptyContainer}>
                    <Ionicons name="checkmark-circle" size={64} color={Colors.success} />
                    <Text style={styles.emptyTitle}>All Done!</Text>
                    <Text style={styles.emptySubtitle}>You've reviewed all combinations</Text>
                    <Text style={styles.statsText}>Saved: {savedCount} | Skipped: {skippedCount}</Text>
                    <TouchableOpacity style={styles.resetButton} onPress={resetCards}>
                        <Text style={styles.resetButtonText}>Review Again</Text>
                    </TouchableOpacity>
                </View>
                <View style={{ height: 110 }} />
            </View>
        );
    }

    return (
        <SafeAreaView style={styles.container}>
            {/* Headers Area (Fixed Position) */}
            <View style={styles.topSection}>
                <ScreenHeader
                    title={t('combinationsTitle', 'Combinations')}
                    subtitle={t('combinationsSubtitle', 'Best possible combination generated by ai')}
                    showWarning={false} // Ensure warning is hidden
                />

                <SofascoreDatePicker selectedDate={selectedDate} onDateChange={setSelectedDate} />
            </View>

            {/* Stack Deck Area */}
            <View style={styles.deckContainer}>
                {loading && (
                    <View style={styles.centerBox}>
                        <ActivityIndicator size="large" color={Colors.primary} />
                        <Text style={styles.loadingText}>Analyzing Combinations...</Text>
                    </View>
                )}

                {!loading && error ? (
                    <View style={styles.centerBox}>
                        <Ionicons name="alert-circle-outline" size={48} color={Colors.traps} />
                        <Text style={styles.errorText}>{error}</Text>
                    </View>
                ) : null}

                {!loading && !error && combinations.length === 0 && !isFinished ? (
                    <View style={styles.centerBox}>
                        <Ionicons name="albums-outline" size={48} color={Colors.textSecondary} />
                        <Text style={styles.emptyText}>No AI Combinations found for this date.</Text>
                    </View>
                ) : null}

                {!loading && !error && combinations.length > 0 && !isFinished ? (
                    <View style={StyleSheet.absoluteFill}>
                        {nextCombo ? (
                            <Animated.View style={[styles.stackedCard, { zIndex: 1 }]}>
                                <CombinationCard combo={nextCombo} />
                            </Animated.View>
                        ) : null}

                        {activeCombo ? (
                            <Animated.View
                                {...panResponder.panHandlers}
                                style={[getCardStyle(), styles.topCard, { zIndex: 2 }]}
                            >
                                <CombinationCard combo={activeCombo} />
                            </Animated.View>
                        ) : null}
                    </View>
                ) : null}
            </View>

            {/* Footer Area */}
            <View style={styles.bottomSection}>
                <Text style={styles.footerText}>
                    {t('infoDisclaimer', 'This analysis is for informational purposes only and shows how historical data behaves. It does not constitute betting advice or a guarantee of outcomes.')}
                </Text>
            </View>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    topSection: {
        paddingTop: 10,
        zIndex: 10,
    },
    pageHeader: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    titleText: {
        fontSize: 26,
        fontWeight: '900',
        color: '#1F2937',
        letterSpacing: 0.5,
        marginBottom: 8,
    },
    subtitleText: {
        fontSize: 14,
        color: '#6B7280',
        lineHeight: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        paddingBottom: 20,
    },
    dateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        marginBottom: 30,
    },
    dateSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F4F6',
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 10,
        width: 180,
        justifyContent: 'space-between',
    },
    dateBtn: {
        padding: 4,
    },
    dateText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
    },
    matchesBadge: {
        backgroundColor: '#57845E',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
    },
    matchesBadgeText: {
        color: '#FFFFFF',
        fontSize: 13,
        fontWeight: '700',
    },
    deckContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1,
    },
    stackedCard: {
        position: 'absolute',
        width: '100%',
        zIndex: 1,
    },
    topCard: {
        position: 'absolute',
        width: '100%',
        zIndex: 2,
    },
    bottomSection: {
        position: 'absolute',
        bottom: 110, // Avoid bottom nav bar overlap
        left: 0,
        right: 0,
        zIndex: 1,
        paddingHorizontal: 20,
        paddingBottom: 20,
    },
    footerContainer: {
        paddingTop: 10,
    },
    footerText: {
        textAlign: 'center',
        fontSize: 11,
        color: '#9CA3AF',
        lineHeight: 16,
    },
    emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12, padding: 20 },
    emptyTitle: { fontSize: 22, fontWeight: '700', color: Colors.text },
    emptySubtitle: { fontSize: 14, color: Colors.textSecondary },
    statsText: { fontSize: 15, fontWeight: '600', color: Colors.primary },
    resetButton: { marginTop: 12, backgroundColor: Colors.primary, paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12 },
    resetButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
    centerBox: { alignItems: 'center', justifyContent: 'center', gap: 12 },
    loadingText: { color: Colors.textSecondary, fontWeight: '600', marginTop: 10 },
    errorText: { color: Colors.traps, fontWeight: '600', textAlign: 'center', paddingHorizontal: 40 },
    emptyText: { color: Colors.textSecondary, fontWeight: '600', textAlign: 'center' },
});
